stages:
- name: Deploy app-db-test1
  steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-db
        version: 0.1.0
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-test1
        targetNamespace: p-v2nzs-pipeline
        answers:
          # 這裡是為了50與140環境測試
          git.host: "10.50.1.53"
          # 這裡是為了告訴要處理的git來源為何
          git.repoName: ${CICD_GIT_REPO_NAME}
          git.branch: ${CICD_GIT_BRANCH}
          db.type: mysql
          # 使用者資料庫管理密碼
          db.username: bear
          db.password: bearisbear
          # 使用者初始想要建立的資料庫名稱
          db.name: health

- name: Deploy app-db-test2
  steps:
    - applyAppConfig:
        catalogTemplate: cattle-global-data:iii-dev-charts3-db
        version: 0.1.0
        name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-test2
        targetNamespace: p-v2nzs-pipeline
        answers:
          # 這裡是為了50與140環境測試
          git.host: "10.50.1.53"
          # 這裡是為了告訴要處理的git來源為何
          git.repoName: ${CICD_GIT_REPO_NAME}
          git.branch: ${CICD_GIT_BRANCH}
          db.type: mysql
          # 使用者資料庫管理密碼
          db.username: bear22
          db.password: bearisbear22
          # 使用者初始想要建立的資料庫名稱
          db.name: health11
